# Libraries

In [77]:
# Stat Libs
import pandas as pd
from pandas.api.types import CategoricalDtype
import pickle
import re

# Stat Libs
import statsmodels.api as sm
from itertools import product
from functools import reduce

# Statistical libs
from sklearn.preprocessing import MultiLabelBinarizer

# Load Data

In [78]:
df1 = pd.read_pickle(r".\df_vizual\df1_vizual.pkl")
df2 = pd.read_pickle(r".\df_vizual\df2_vizual.pkl")
df3 = pd.read_pickle(r".\df_vizual\df3_vizual.pkl")
df4 = pd.read_pickle(r".\df_vizual\df4_vizual.pkl")

p_cl1 = pd.read_pickle(r".\p_values\p_cl1_vizual.pkl")
p_cl2 = pd.read_pickle(r".\p_values\p_cl2_vizual.pkl")
p_cl3 = pd.read_pickle(r".\p_values\p_cl3_vizual.pkl")
p_cl4 = pd.read_pickle(r".\p_values\p_cl4_vizual.pkl")

In [79]:
dfis = [df1, df2, df3, df4]
iss = [1, 2, 3, 4]

# Dummies
"_List” data: List element data, were encoded through dummy creation. The problem was that list-element data cannot be used from models. Firstly, list-element rows were exploded to one row per element of list. However, this inflates sample size, as rows increase and duplicate for same nct_id if more than one element occur in a list-row. For this reason, these data were then grouped by nct_id, so number of rows remained the same as initial datasets (df0, df1, df2, df3, df4, df5).

In [80]:
# Alternatively for List element columns 
mlb = MultiLabelBinarizer()

In [81]:
## Dummies
def fun_dum_enc(dfi, cols):
    for col in cols:  
        df_expl = dfi.copy()
        df_expl = df_expl.explode(col)

        df_expl[col] = df_expl[col].astype('category') 
        df_expl[col] = df_expl[col].cat.remove_unused_categories()
        df_expl[col] = df_expl[col].astype('str') #str cause of error in encoding. After astype(cat) so to drop unused categories

        dummies = pd.get_dummies(df_expl[col], drop_first = False, dtype = int, prefix = col , prefix_sep='_')
        
        dummies.index = df_expl.index # ensure same indexing with df_expl
        dummies = dummies.groupby(dummies.index).sum().clip(upper = 1) 
        # clip: if a row has double entry data ['UNSPES', 'UNSPES'] it avoids double vounting with sum().

        dfi = pd.concat([dfi.drop(columns = [col], axis = 1), dummies], axis = 1)  
    return dfi

### Cols
def fun_dum_cols(dfis):  # In case they are not the same.
    dum_cols = []
    for dfi in dfis: # loop inputed in case dfis have not all the same columns. # * Plus not to run function into funtion.
        dum_cols = dum_cols + [[col for col in dfi.columns if '_List' in col]]
    return dum_cols

dum_cols = fun_dum_cols(dfis) 

# Apply
# * loop so not to run function into function
df1 = fun_dum_enc(df1, dum_cols[0])
df2 = fun_dum_enc(df2, dum_cols[1])
df3 = fun_dum_enc(df3, dum_cols[2])
df4 = fun_dum_enc(df4, dum_cols[3])


# Example
display(dum_cols[0])
df1[[col for col in df1.columns if '_list' in col.lower()]] #.head()  # Transposed for better view

['Sex_List',
 'Age_List',
 'Intervention_Type_List',
 'Intervention_Route_List',
 'Conditions_Detail_List',
 'Adverse_List',
 'Allocation_List',
 'Intervention_Model_List',
 'Masking_List',
 'Primary_Purpose_List',
 'Continents_List']

,Sex_List_ALL,Sex_List_FEMALE,Sex_List_MALE,Age_List_ADULT,Age_List_CHILD,Age_List_OLDER_ADULT,Intervention_Type_List_BEHAVIORAL,Intervention_Type_List_BIOLOGICAL,Intervention_Type_List_DEVICE,Intervention_Type_List_DIETARY_SUPPLEMENT,...,Primary_Purpose_List_BASIC_SCIENCE,Primary_Purpose_List_DIAGNOSTIC,Primary_Purpose_List_PREVENTION,Primary_Purpose_List_PRIM_PURP_OTHER,Primary_Purpose_List_SUPPORTIVE_CARE,Primary_Purpose_List_TREATMENT,Continents_List_Asia,Continents_List_Cont_Other,Continents_List_Europe,Continents_List_North America
0,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
1,0,0,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
3,1,0,0,1,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
4,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21824,1,0,0,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
21825,1,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
21826,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
21827,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
21828,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0

## Drop First
- Drop first was not done through get_dummies command, so to choose the column to drop, based on its characterisic. e.g., drop phase 0 is preferred that to drop phase 3.

In [82]:
dfis = [df1, df2, df3, df4]
iss = [1, 2, 3, 4]

In [83]:

def fun_drop_first(dfi):
    dum_cols = [col for col in dfi.columns if '_list' in col.lower()]
    
    keywords = ['other', 'none', 'sex_list_all', 'age_list_child', 'na_randomize', 'single_grou']
    drop_cols = [col for col in dum_cols if any(key in col.lower() for key in keywords) and '_x_' not in col]
    
    dfi = dfi.drop(columns = drop_cols, axis = 1)
    return dfi

df1 = fun_drop_first(df1)
df2 = fun_drop_first(df2)
df3 = fun_drop_first(df3)
df4 = fun_drop_first(df4)

# Example Check
df1.columns.values.tolist()

['Study_Status_Bin',
 'Funder_Industry_Bin',
 'Placebo_Bin',
 'Standard_Care_Bin',
 'Healthy_Bin',
 'Adverse_Counts_Log',
 'Arm_Counts_Log',
 'City_Counts_Log',
 'Enrollment_Counts_Log',
 'Sex_List_FEMALE',
 'Sex_List_MALE',
 'Age_List_ADULT',
 'Age_List_OLDER_ADULT',
 'Intervention_Type_List_BEHAVIORAL',
 'Intervention_Type_List_BIOLOGICAL',
 'Intervention_Type_List_DEVICE',
 'Intervention_Type_List_DIETARY_SUPPLEMENT',
 'Intervention_Type_List_DRUG',
 'Intervention_Type_List_INTERV_UNSPES',
 'Intervention_Type_List_PROCEDURE',
 'Intervention_Route_List_Injection',
 'Intervention_Route_List_Oral',
 'Intervention_Route_List_Surgical',
 'Intervention_Route_List_Topical',
 'Conditions_Detail_List_Bacterial, Mycoses, Virus Diseases',
 'Conditions_Detail_List_Cardiovascular',
 'Conditions_Detail_List_Digestive System, Nutritional, Metabolic',
 'Conditions_Detail_List_Endocrine System',
 'Conditions_Detail_List_Eye',
 'Conditions_Detail_List_Health Care, Therapeutics',
 'Conditions_Detail_List_Hemic, Lymphatic, Immune System',
 'Conditions_Detail_List_Hereditary, Neonatal, Abnormalities',
 'Conditions_Detail_List_Musculoskeletal, Neural',
 'Conditions_Detail_List_Neoplasms',
 'Conditions_Detail_List_Nervous System',
 'Conditions_Detail_List_Pathological Conditions, Signs, Symptoms',
 'Conditions_Detail_List_Phenomena, Processes',
 'Conditions_Detail_List_Psychiatry, Psychology, Anthropology, Sociology',
 'Conditions_Detail_List_Respiratory, Circulatory',
 'Conditions_Detail_List_Skin, Tissue, Wounds',
 'Conditions_Detail_List_Stomatognathic, Otorhinolaryngologic',
 'Conditions_Detail_List_Urogenital, Pregnancy',
 'Adverse_List_Adv_Death',
 'Adverse_List_Adv_Serious',
 'Adverse_List_Adv_Unspecified',
 'Allocation_List_NON_RANDOMIZED',
 'Allocation_List_RANDOMIZED',
 'Intervention_Model_List_CROSSOVER',
 'Intervention_Model_List_FACTORIAL, SEQUENTIAL',
 'Intervention_Model_List_PARALLEL',
 'Masking_List_DOUBLE',
 'Masking_List_QUADRUPLE',
 'Masking_List_SINGLE',
 'Masking_List_TRIPLE',
 'Primary_Purpose_List_BASIC_SCIENCE',
 'Primary_Purpose_List_DIAGNOSTIC',
 'Primary_Purpose_List_PREVENTION',
 'Primary_Purpose_List_SUPPORTIVE_CARE',
 'Primary_Purpose_List_TREATMENT',
 'Continents_List_Asia',
 'Continents_List_Europe',
 'Continents_List_North America']

# Binary

In [84]:
# Binary Encoding
def fun_bin_enc(dfi, cols):
    dfi = dfi.copy()
    for col in cols:
        cats = CategoricalDtype(categories = sorted(dfi[col].dropna().unique()), ordered = False)
        dfi[col] = dfi[col].astype(cats).cat.codes
    return dfi


### Cols
def fun_bin_cols(dfis):
    bin_cols = []
    for dfi in dfis:
        bin_cols = bin_cols + [[col for col in dfi.columns if '_Categ' in col.lower() or '_Bin' in col]] 
    return bin_cols

# Apply
bin_cols = fun_bin_cols(dfis)

df1 = fun_bin_enc(df1, bin_cols[0])
df2 = fun_bin_enc(df2, bin_cols[1])
df3 = fun_bin_enc(df3, bin_cols[2])
df4 = fun_bin_enc(df4, bin_cols[3])

# Example
display(df1['Study_Status_Bin'].value_counts())  # Completed = 0, Terminated = 1
display(bin_cols[0])  # bin_cols[0] --> bin_cols of df1
display(df1[bin_cols[0]])

Study_Status_Bin
0    18646
1     3183
Name: count, dtype: int64

['Study_Status_Bin',
 'Funder_Industry_Bin',
 'Placebo_Bin',
 'Standard_Care_Bin',
 'Healthy_Bin']

,Study_Status_Bin,Funder_Industry_Bin,Placebo_Bin,Standard_Care_Bin,Healthy_Bin
0,0,1,0,0,1
1,0,0,1,0,1
2,0,1,0,0,0
3,0,1,0,0,1
4,1,1,1,1,0
...,...,...,...,...,...
21824,0,1,0,0,0
21825,0,1,0,0,1
21826,0,1,0,0,1
21827,0,0,1,0,0
21828,0,0,0,0,1

# Interactions

In [85]:
dfis = [df1, df2, df3, df4]
iss = [1, 2, 3, 4]

In [86]:
# Intreaction of Categorical_x_Binary
def fun_inter(dfi, col1, col2, stip):

    cols1 = [col for col in dfi.columns if col1 in col]  # All dfs have the same columns
    cols2 = [col for col in dfi.columns if col2 in col]

    for col1, col2 in product(cols1, cols2):
        inter_col1 = f"{col1}_x_{col2}"
        dfi[inter_col1] = dfi[col1] * dfi[col2]
        inter_col = re.sub(stip, "", inter_col1)
        dfi.rename(columns = {inter_col1: inter_col}, inplace=True)
        
    return dfi
    
df1 = fun_inter(df1, 'Intervention_Type_List', 'Funder_Industry_Bin', r"Intervention_Type_List_|_Bin" )
df2 = fun_inter(df2, 'Intervention_Type_List', 'Funder_Industry_Bin', r"Intervention_Type_List_|_Bin")
df3 = fun_inter(df3, 'Intervention_Type_List', 'Funder_Industry_Bin', r"Intervention_Type_List_|_Bin")
df4 = fun_inter(df4, 'Intervention_Type_List', 'Funder_Industry_Bin', r"Intervention_Type_List_|_Bin")

df1 = df1.rename(columns = {col: col + "_List" if "_x_Funder_Industry" in col else col for col in df1.columns})
df2 = df2.rename(columns = {col: col + "_List" if "_x_Funder_Industry" in col else col for col in df2.columns})
df3 = df3.rename(columns = {col: col + "_List" if "_x_Funder_Industry" in col else col for col in df3.columns})
df4 = df4.rename(columns = {col: col + "_List" if "_x_Funder_Industry" in col else col for col in df4.columns})

df1 = fun_inter(df1, 'Enrollment_Counts_Log', 'Conditions_Detail_List', r"Conditions_Detail_List|_Counts" )
df2 = fun_inter(df2, 'Enrollment_Counts_Log', 'Conditions_Detail_List', r"Conditions_Detail_List|_Counts")
df3 = fun_inter(df3, 'Enrollment_Counts_Log', 'Conditions_Detail_List', r"Conditions_Detail_List|_Counts")
df4 = fun_inter(df4, 'Enrollment_Counts_Log', 'Conditions_Detail_List', r"Conditions_Detail_List|_Counts")

In [87]:
dfis = [df1, df2, df3, df4]
iss = [1, 2, 3, 4]

# Pivot
pivots_inter = []

for i, dfi in zip(iss, dfis):
    pivot = dfi.pivot_table(
        index = "Study_Status_Bin",
        values = [col for col in dfi.columns if '_x_' in col],
        aggfunc = "sum", 
        observed = False)
    
    pivot_inter_1 = pivot.T
    pivot_inter_1.columns = [f"df{i}_{outcome}" for outcome in pivot_inter_1.columns]  # Optional: label by df index
    
    pivots_inter.append(pivot_inter_1)

pivot_inter1 = pivots_inter[0]
pivot_inter2 = pivots_inter[1]
pivot_inter3 = pivots_inter[2]
pivot_inter4 = pivots_inter[3]

# Checks
inter_cols = [col for col in df4.columns if '_x_' in col]  # i have the world other in too many data levels !!
display(len(inter_cols))  # Must have created 1

pivot_inter = pd.concat(pivots_inter, axis=1)
pivot_inter['Sum_Counts'] = pivot_inter.sum(axis = 1)
pivot_inter.sort_values(by = 'Sum_Counts')

25

,df1_0,df1_1,df2_0,df2_1,df3_0,df3_1,df4_0,df4_1,Sum_Counts
BEHAVIORAL_x_Funder_Industry_List,4.000000,1.000000,32.000000,10.000000,14.000000,2.000000,7.000000,3.000000,73.000000
DIETARY_SUPPLEMENT_x_Funder_Industry_List,44.000000,4.000000,69.000000,13.000000,36.000000,9.000000,34.000000,4.000000,213.000000
PROCEDURE_x_Funder_Industry_List,43.000000,14.000000,61.000000,15.000000,78.000000,14.000000,26.000000,9.000000,260.000000
INTERV_UNSPES_x_Funder_Industry_List,138.000000,32.000000,88.000000,47.000000,93.000000,24.000000,27.000000,7.000000,456.000000
DEVICE_x_Funder_Industry_List,148.000000,20.000000,112.000000,42.000000,181.000000,44.000000,185.000000,42.000000,774.000000
BIOLOGICAL_x_Funder_Industry_List,1103.000000,224.000000,872.000000,233.000000,1125.000000,124.000000,264.000000,17.000000,3962.000000
"Enrollment_Log_x__Health Care, Therapeutics",1041.991745,43.851619,1092.901654,135.442873,1026.158460,81.811720,1375.154222,148.853345,4946.165637
"Enrollment_Log_x__Stomatognathic, Otorhinolaryngologic",789.207452,58.343280,1963.239629,208.303713,1961.651376,159.066275,1815.448562,88.886819,7044.147106
Enrollment_Log_x__Eye,787.074103,69.745108,2020.541622,278.568113,2385.330365,238.025981,1682.740422,115.778821,7577.804534
"Enrollment_Log_x__Phenomena, Processes",2273.347208,123.566184,2899.411277,341.532279,2155.413387,222.544629,2777.689110,278.518810,11072.022885
"Enrollment_Log_x__Hereditary, Neonatal, Abnormalities",2289.100068,234.647566,3642.952169,713.229541,3236.353170,526.240084,1308.559604,138.397553,12089.479754
Enrollment_Log_x__Endocrine System,4748.278957,508.702500,4306.067832,756.007583,4787.983903,563.287652,3904.296250,296.073184,19870.697860
Enrollment_Log_x__Cardiovascular,3300.777672,438.999251,5403.987826,890.129312,5763.750287,995.094307,6516.849552,768.647793,24078.235999
"Enrollment_Log_x__Musculoskeletal, Neural",2900.028690,194.473957,5619.467357,800.159448,6953.738913,733.371761,8339.707904,766.461643,26307.409673
"Enrollment_Log_x__Urogenital, Pregnancy",5071.011783,699.223990,6601.059828,1237.255171,6060.719192,806.213256,5259.260635,587.208483,26321.952338
DRUG_x_Funder_Industry_List,11879.000000,1530.000000,5744.000000,1766.000000,5738.000000,1111.000000,1548.000000,285.000000,29601.000000
"Enrollment_Log_x__Respiratory, Circulatory",6552.630830,888.720877,8425.911772,1866.116315,8859.541977,1112.596128,4945.380337,512.725407,33163.623644
"Enrollment_Log_x__Skin, Tissue, Wounds",6301.661065,1005.077303,10897.076404,2115.425868,9241.359028,969.776938,5002.984862,586.010566,36119.372033
"Enrollment_Log_x__Hemic, Lymphatic, Immune System",7935.234074,1444.865574,10105.167580,2071.186894,9114.348093,1120.161246,4258.038825,475.937054,36524.939340
"Enrollment_Log_x__Psychiatry, Psychology, Anthropology, Sociology",5250.741153,346.292678,9231.051171,1115.661329,8412.335478,1075.815892,10304.754178,958.924992,36695.576873
Enrollment_Log_x__Nervous System,5240.405247,509.901939,9633.944086,1526.032506,9904.619021,1550.346087,10489.923872,965.930700,39821.103459
"Enrollment_Log_x__Bacterial, Mycoses, Virus Diseases",8546.752056,597.091289,9093.843884,1415.470863,11740.545162,997.059126,7319.024119,634.915280,40344.701777
"Enrollment_Log_x__Digestive System, Nutritional, Metabolic",10903.073169,1166.440348,12768.913964,2254.060631,12459.301389,1531.728767,8964.790009,832.377235,50880.685512
Enrollment_Log_x__Neoplasms,13108.566412,3489.246052,18609.718377,4670.808581,8413.573805,1630.892876,3188.660101,376.547489,53488.013694
"Enrollment_Log_x__Pathological Conditions, Signs, Symptoms",8736.912133,1204.264392,15636.759313,2424.178393,16472.508643,1988.308725,17434.486142,1615.366748,65512.784490

In [88]:
def fun_zeros(pivot_merged, count, missing):

    num_cols = pivot_merged.select_dtypes(include='number')
    mask = num_cols < count
    if missing == True:
        mask |= num_cols.isna()
    sparse = pivot_merged[mask.any(axis=1)]
    return sparse

In [89]:
fun_zeros(pivot_inter, 10, False)

,df1_0,df1_1,df2_0,df2_1,df3_0,df3_1,df4_0,df4_1,Sum_Counts
BEHAVIORAL_x_Funder_Industry_List,4.0,1.0,32.0,10.0,14.0,2.0,7.0,3.0,73.0
DIETARY_SUPPLEMENT_x_Funder_Industry_List,44.0,4.0,69.0,13.0,36.0,9.0,34.0,4.0,213.0
INTERV_UNSPES_x_Funder_Industry_List,138.0,32.0,88.0,47.0,93.0,24.0,27.0,7.0,456.0
PROCEDURE_x_Funder_Industry_List,43.0,14.0,61.0,15.0,78.0,14.0,26.0,9.0,260.0

In [90]:
def fun_drop_inter(dfi):
    cols_to_merge = ['BEHAVIORAL_x_Funder_Industry_List', 'DIETARY_SUPPLEMENT_x_Funder_Industry_List', 
        'PROCEDURE_x_Funder_Industry_List', 'INTERV_UNSPES_x_Funder_Industry_List']

    dfi['INTERV_UNSPES_x_Funder_Industry_List'] = dfi[cols_to_merge].max(axis=1)  
    dfi = dfi.drop(columns=[col for col in cols_to_merge if col != 'INTERV_UNSPES_x_Funder_Industry_List'])
    return dfi

df1 = fun_drop_inter(df1)
df2 = fun_drop_inter(df2)
df3 = fun_drop_inter(df3)
df4 = fun_drop_inter(df4)

df4[[col for col in df4.columns if '_x_Funder' in col]].columns.to_list()

['BIOLOGICAL_x_Funder_Industry_List',
 'DEVICE_x_Funder_Industry_List',
 'DRUG_x_Funder_Industry_List',
 'INTERV_UNSPES_x_Funder_Industry_List']

# p_values

In [91]:
p_cls = [p_cl1[['Variable', 'df1-Stat_Sig']], 
         p_cl2[['Variable', 'df2-Stat_Sig']], 
         p_cl3[['Variable', 'df3-Stat_Sig']], 
         p_cl4[['Variable', 'df4-Stat_Sig']]]

p_cl = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), p_cls)
p_cl[p_cl['Variable'].isin(df1.columns)]

                 Variable df1-Stat_Sig df2-Stat_Sig df3-Stat_Sig df4-Stat_Sig
4      Adverse_Counts_Log     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
13        City_Counts_Log     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
21  Enrollment_Counts_Log     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
26    Funder_Industry_Bin     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
28            Healthy_Bin     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
46            Placebo_Bin     Stat_Sig     Stat_Sig     Stat_Sig            -
54      Standard_Care_Bin     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig

In [92]:
p_cl[~p_cl['Variable'].str.contains('Adv_Syst|Adverse_System|Continent_Counts|Country_Counts')]

                 Variable df1-Stat_Sig df2-Stat_Sig df3-Stat_Sig df4-Stat_Sig
0                   ADULT     Stat_Sig            -            -            -
1               Adv_Death            -     Stat_Sig            -            -
2             Adv_Serious     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
3         Adv_Unspecified     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
4      Adverse_Counts_Log     Stat_Sig     Stat_Sig     Stat_Sig     Stat_Sig
..                    ...          ...          ...          ...          ...
56               Surgical     Stat_Sig     Stat_Sig     Stat_Sig            -
57              TREATMENT     Stat_Sig     Stat_Sig            -            -
58                 TRIPLE     Stat_Sig     Stat_Sig            -     Stat_Sig
59                Topical     Stat_Sig     Stat_Sig            -            -
60  Urogenital, Pregnancy            -            -     Stat_Sig     Stat_Sig

[61 rows x 5 columns]

# Save Dfs

In [93]:
df1.to_pickle(r".\df_dummies\df1_dummies.pkl")
df2.to_pickle(r".\df_dummies\df2_dummies.pkl")
df3.to_pickle(r".\df_dummies\df3_dummies.pkl")
df4.to_pickle(r".\df_dummies\df4_dummies.pkl")

In [94]:
display(df1.shape)
display(df2.shape)
display(df3.shape)
display(df4.shape)

(21829, 84)

(21228, 84)

(13966, 84)

(13246, 84)