# Libraries

In [1]:
import pandas as pd
import numpy as np
from functools import reduce

# Load Tables

In [2]:
df = pd.read_pickle(r".\df_data\df.pkl")
df1 = pd.read_pickle(r".\df_data\df1.pkl")
df2 = pd.read_pickle(r".\df_data\df2.pkl")
df3 = pd.read_pickle(r".\df_data\df3.pkl")
df4 = pd.read_pickle(r".\df_data\df4.pkl")

medians = pd.read_pickle(r".\df_data\medians.pkl")

pivots1 = pd.read_pickle(r".\p_values\pivots1_vizual.pkl")
pivots2 = pd.read_pickle(r".\p_values\pivots2_vizual.pkl")
pivots3 = pd.read_pickle(r".\p_values\pivots3_vizual.pkl")
pivots4 = pd.read_pickle(r".\p_values\pivots4_vizual.pkl")

pivots_train1 = pd.read_pickle(r".\p_values\pivots1_vizual_train.pkl")
pivots_train2 = pd.read_pickle(r".\p_values\pivots2_vizual_train.pkl")
pivots_train3 = pd.read_pickle(r".\p_values\pivots3_vizual_train.pkl")
pivots_train4 = pd.read_pickle(r".\p_values\pivots4_vizual_train.pkl")

p_cl_train1 = pd.read_pickle(r".\p_values\p_cl1_vizual_train.pkl")
p_cl_train2 = pd.read_pickle(r".\p_values\p_cl2_vizual_train.pkl")
p_cl_train3 = pd.read_pickle(r".\p_values\p_cl3_vizual_train.pkl")
p_cl_train4 = pd.read_pickle(r".\p_values\p_cl4_vizual_train.pkl")

chi_train1 = pd.read_pickle(r".\p_values\chi1_vizual_train.pkl")
chi_train2 = pd.read_pickle(r".\p_values\chi2_vizual_train.pkl")
chi_train3 = pd.read_pickle(r".\p_values\chi3_vizual_train.pkl")
chi_train4 = pd.read_pickle(r".\p_values\chi4_vizual_train.pkl")

mann_train1 = pd.read_pickle(r".\p_values\mann_whit1_vizual_train.pkl")
mann_train2 = pd.read_pickle(r".\p_values\mann_whit2_vizual_train.pkl")
mann_train3 = pd.read_pickle(r".\p_values\mann_whit3_vizual_train.pkl")
mann_train4 = pd.read_pickle(r".\p_values\mann_whit4_vizual_train.pkl")

aic_cont_train1 = pd.read_pickle(r".\p_values\aic_counts1_vizual_train.pkl")
aic_cont_train2 = pd.read_pickle(r".\p_values\aic_counts2_vizual_train.pkl")
aic_cont_train3 = pd.read_pickle(r".\p_values\aic_counts3_vizual_train.pkl")
aic_cont_train4 = pd.read_pickle(r".\p_values\aic_counts4_vizual_train.pkl")

aic_categ_train1 = pd.read_pickle(r".\p_values\aic_categ1_vizual_train.pkl")
aic_categ_train2 = pd.read_pickle(r".\p_values\aic_categ2_vizual_train.pkl")
aic_categ_train3 = pd.read_pickle(r".\p_values\aic_categ3_vizual_train.pkl")
aic_categ_train4 = pd.read_pickle(r".\p_values\aic_categ4_vizual_train.pkl")

my_terminations = pd.read_pickle(r".\df_sql\my_terminations.pkl")

# Medians (Full data)

In [3]:
medians[['Enrollment', 'Adverse', 'Arm', 'City', 'Country', 'Completion_Gap']]

        Enrollment  Adverse  Arm  City  Country  Completion_Gap
df1           29.0      0.0  2.0   1.0      1.0            11.0
df2           50.0      0.0  2.0   2.0      1.0            26.0
df3          204.0      1.0  2.0   9.0      1.0            24.0
df4           68.0      0.0  2.0   1.0      1.0            21.0
Mean         87.75     0.25  2.0  3.25      1.0            20.5
Median        59.0      0.0  2.0   1.5      1.0            22.5

In [4]:
# Columns for which distribution is more wide --> May be kept as Log
medians_categ = medians.loc[:, medians.loc["Median"] > 5]
categ_cols = medians_categ.columns.to_list()
drop_categ_cols = [col + "_Categ" for col in categ_cols]

# Columns with almost all distribution around lower values e.g., 0, 1 ,2
medians_log = medians.loc[:, medians.loc["Median"] < 5]
drop_log_cols = [col for col in df1.columns 
                 if "_Log" in col and any(name in col for name in medians_log)]

display(drop_log_cols)

['Funder_Counts_Log',
 'Adverse_Counts_Log',
 'Adverse_System_Counts_Log',
 'Arm_Counts_Log',
 'City_Counts_Log',
 'Continent_Counts_Log',
 'Country_Counts_Log']

# Pivots

## Pivots (Full Data)

In [5]:
pivots1.index.names = ['Variable', 'Level']
pivots2.index.names = ['Variable', 'Level']
pivots3.index.names = ['Variable', 'Level']
pivots4.index.names = ['Variable', 'Level']
pivots1.index.names

FrozenList(['Variable', 'Level'])

In [6]:
pivots = pivots1.merge(pivots2, on = ['Variable','Level'], how = 'outer')
pivots = pivots.merge(pivots3, on = ['Variable','Level'], how = 'outer')
pivots = pivots.merge(pivots4, on = ['Variable','Level'], how = 'outer')
pivots

Study_Status_Bin                  df1_COMPLETED  df1_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No         15623.0          1899.0
                     Adverse_Yes         3023.0           467.0
Adverse_List         Adv_Death           1393.0           270.0
                     Adv_None           15547.0          1891.0
                     Adv_Serious         1152.0           310.0
...                                         ...             ...
Primary_Purpose_List TREATMENT          11515.0          1904.0
Sex_List             FEMALE             15842.0          2231.0
                     MALE               17884.0          2248.0
Standard_Care_Bin    Soc_No             18425.0          2285.0
                     Soc_Yes              221.0            81.0

Study_Status_Bin                  df2_COMPLETED  df2_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          8512.0          1812.0
                     Adverse_Yes         7292.0          2131.0
Adverse_List         Adv_Death           4067.0          1262.0
                     Adv_None            8395.0          1756.0
                     Adv_Serious         5527.0          1552.0
...                                         ...             ...
Primary_Purpose_List TREATMENT          13236.0          3496.0
Sex_List             FEMALE             15171.0          3777.0
                     MALE               14519.0          3690.0
Standard_Care_Bin    Soc_No             15171.0          3699.0
                     Soc_Yes              633.0           244.0

Study_Status_Bin                  df3_COMPLETED  df3_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          5677.0           885.0
                     Adverse_Yes         5880.0           875.0
Adverse_List         Adv_Death           3860.0           573.0
                     Adv_None            5586.0           864.0
                     Adv_Serious         5173.0           730.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           9355.0          1518.0
Sex_List             FEMALE             11221.0          1705.0
                     MALE               10584.0          1630.0
Standard_Care_Bin    Soc_No             11089.0          1623.0
                     Soc_Yes              468.0           137.0

Study_Status_Bin                  df4_COMPLETED  df4_TERMINATED
Variable             Level
Adverse_Bin          Adverse_No          8210.0          1086.0
                     Adverse_Yes         2727.0           397.0
Adverse_List         Adv_Death           1585.0           235.0
                     Adv_None            7904.0          1020.0
                     Adv_Serious         1591.0           195.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           7459.0          1081.0
Sex_List             FEMALE             10594.0          1453.0
                     MALE                9670.0          1323.0
Standard_Care_Bin    Soc_No             10508.0          1375.0
                     Soc_Yes              429.0           108.0

[158 rows x 8 columns]

## Pivots (Train Data)

In [7]:
pivots_train1.index.names = ['Variable', 'Level']
pivots_train2.index.names = ['Variable', 'Level']
pivots_train3.index.names = ['Variable', 'Level']
pivots_train4.index.names = ['Variable', 'Level']

In [8]:
pivots_train = pivots_train1.merge(pivots_train2, on = ['Variable','Level'], how = 'outer')
pivots_train = pivots_train.merge(pivots_train3, on = ['Variable','Level'], how = 'outer')
pivots_train = pivots_train.merge(pivots_train4, on = ['Variable','Level'], how = 'outer')
pivots_train

Study_Status_Bin                  df1_COMPLETED  df1_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No         12504.0          1522.0
                     Adverse_Yes         2412.0           371.0
Adverse_List         Adv_Death           1118.0           215.0
                     Adv_None           12445.0          1514.0
                     Adv_Serious          934.0           247.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           9211.0          1525.0
Sex_List             FEMALE             12676.0          1780.0
                     MALE               14328.0          1797.0
Standard_Care_Bin    Soc_No             14744.0          1827.0
                     Soc_Yes              172.0            66.0

Study_Status_Bin                  df2_COMPLETED  df2_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          6807.0          1447.0
                     Adverse_Yes         5836.0          1707.0
Adverse_List         Adv_Death           3271.0           992.0
                     Adv_None            6716.0          1408.0
                     Adv_Serious         4436.0          1228.0
...                                         ...             ...
Primary_Purpose_List TREATMENT          10589.0          2800.0
Sex_List             FEMALE             12149.0          3022.0
                     MALE               11609.0          2936.0
Standard_Care_Bin    Soc_No             12159.0          2960.0
                     Soc_Yes              484.0           194.0

Study_Status_Bin                  df3_COMPLETED  df3_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          4532.0           693.0
                     Adverse_Yes         4713.0           715.0
Adverse_List         Adv_Death           3089.0           470.0
                     Adv_None            4456.0           676.0
                     Adv_Serious         4146.0           600.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           7482.0          1219.0
Sex_List             FEMALE              8977.0          1364.0
                     MALE                8476.0          1305.0
Standard_Care_Bin    Soc_No              8885.0          1296.0
                     Soc_Yes              360.0           112.0

Study_Status_Bin                  df4_COMPLETED  df4_TERMINATED
Variable             Level
Adverse_Bin          Adverse_No          6596.0           872.0
                     Adverse_Yes         2154.0           314.0
Adverse_List         Adv_Death           1254.0           194.0
                     Adv_None            6341.0           817.0
                     Adv_Serious         1257.0           160.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           5954.0           855.0
Sex_List             FEMALE              8466.0          1160.0
                     MALE                7726.0          1054.0
Standard_Care_Bin    Soc_No              8406.0          1099.0
                     Soc_Yes              344.0            87.0

[158 rows x 8 columns]

# Train Data

## P_values

In [9]:
p_cls_train = [p_cl_train1[['Variable', 'df1_Stat_Sig']].rename(columns = {'df1_Stat_Sig': 'df1'}), 
         p_cl_train2[['Variable', 'df2_Stat_Sig']].rename(columns = {'df2_Stat_Sig': 'df2'}), 
         p_cl_train3[['Variable', 'df3_Stat_Sig']].rename(columns = {'df3_Stat_Sig': 'df3'}), 
         p_cl_train4[['Variable', 'df4_Stat_Sig']].rename(columns = {'df4_Stat_Sig': 'df4'})]

p_cl_train = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), p_cls_train)
p_cl_train.index.name = 'p_cl'
p_cl_train

,Variable,df1,df2,df3,df4
p_cl,,,,,
0,ADULT,Stat_Sig,-,-,-
1,Adv_Death,-,Stat_Sig,-,Stat_Sig
2,Adv_Serious,Stat_Sig,Stat_Sig,Stat_Sig,Stat_Sig
3,"Adv_Syst_Blood, Lymphatic, Endocrine",Stat_Sig,Stat_Sig,Stat_Sig,-
4,Adv_Syst_Cardio,-,Stat_Sig,-,-
...,...,...,...,...,...
110,Surgical,Stat_Sig,Stat_Sig,Stat_Sig,-
111,TREATMENT,Stat_Sig,Stat_Sig,Stat_Sig,-
112,TRIPLE,Stat_Sig,Stat_Sig,-,Stat_Sig
113,Topical,-,-,-,-
114,"Urogenital, Pregnancy",-,-,-,Stat_Sig

## Chi2

In [10]:
chi_trains = [chi_train1[['Variable', 'df1_Stat_Sig']].rename(columns = {'df1_Stat_Sig': 'df1'}), 
         chi_train2[['Variable', 'df2_Stat_Sig']].rename(columns = {'df2_Stat_Sig': 'df2'}), 
         chi_train3[['Variable', 'df3_Stat_Sig']].rename(columns = {'df3_Stat_Sig': 'df3'}), 
         chi_train4[['Variable', 'df4_Stat_Sig']].rename(columns = {'df4_Stat_Sig': 'df4'})]

chi_train = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), chi_trains)
chi_train.index.name = 'Chi2'
chi_train

                      Variable       df1       df2       df3       df4
Chi2
0                  Adverse_Bin  Stat_Sig  Stat_Sig         -         -
1         Adverse_System_Categ  Stat_Sig  Stat_Sig         -         -
2               Allocation_Bin  Stat_Sig  Stat_Sig         -         -
3                    Arm_Categ  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
4                   City_Categ  Stat_Sig         -  Stat_Sig         -
5         Completion_Gap_Categ  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
6              Continent_Categ  Stat_Sig  Stat_Sig  Stat_Sig         -
7                 Covid_19_Bin         -  Stat_Sig  Stat_Sig         -
8             Enrollment_Categ  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
9                   Funder_Bin  Stat_Sig         -  Stat_Sig         -
10         Funder_Industry_Bin  Stat_Sig  Stat_Sig         -         -
11                  Global_Bin  Stat_Sig         -  Stat_Sig         -
12                 Healthy_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
13    Intervention_Route_Categ  Stat_Sig  Stat_Sig         -  Stat_Sig
14     Intervention_Type_Categ  Stat_Sig  Stat_Sig         -         -
15                 Placebo_Bin  Stat_Sig  Stat_Sig  Stat_Sig         -
16           Standard_Care_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig

## Mann Whitney

In [11]:
mann_trains = [mann_train1[['Variable', 'df1_Stat_Sig']].rename(columns = {'df1_Stat_Sig': 'df1'}), 
         mann_train2[['Variable', 'df2_Stat_Sig']].rename(columns = {'df2_Stat_Sig': 'df2'}), 
         mann_train3[['Variable', 'df3_Stat_Sig']].rename(columns = {'df3_Stat_Sig': 'df3'}), 
         mann_train4[['Variable', 'df4_Stat_Sig']].rename(columns = {'df4_Stat_Sig': 'df4'})]

mann_train = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), mann_trains)
mann_train.index.name = 'Mann'
mann_train

                       Variable       df1       df2       df3       df4
Mann
0                Adverse_Counts  Stat_Sig         -  Stat_Sig         -
1            Adverse_Counts_Log  Stat_Sig         -  Stat_Sig         -
2         Adverse_System_Counts  Stat_Sig  Stat_Sig         -         -
3     Adverse_System_Counts_Log  Stat_Sig  Stat_Sig         -         -
4                    Arm_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
5                Arm_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
6                   City_Counts  Stat_Sig         -  Stat_Sig         -
7               City_Counts_Log  Stat_Sig         -  Stat_Sig         -
8         Completion_Gap_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
9            Completion_Gap_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
10             Continent_Counts  Stat_Sig  Stat_Sig  Stat_Sig         -
11         Continent_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig         -
12               Country_Counts  Stat_Sig  Stat_Sig  Stat_Sig         -
13           Country_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig         -
14            Enrollment_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
15        Enrollment_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
16                Funder_Counts  Stat_Sig         -  Stat_Sig         -
17            Funder_Counts_Log  Stat_Sig         -  Stat_Sig         -
18    Intervention_Route_Counts  Stat_Sig  Stat_Sig         -  Stat_Sig
19     Intervention_Type_Counts  Stat_Sig  Stat_Sig         -         -

# AIC

## AIC Counts

In [12]:
aic_cont_train1['Phase'] = 'df1'
aic_cont_train2['Phase'] = 'df2'
aic_cont_train3['Phase'] = 'df3'
aic_cont_train4['Phase'] = 'df4'

aic_cont_trains = [aic_cont_train1, 
         aic_cont_train2, 
         aic_cont_train3, 
         aic_cont_train4]

aic_cont_train = pd.concat(aic_cont_trains, axis = 0)
aic_cont_train = pd.concat([aic_cont_train['Phase'], aic_cont_train.drop(columns = ['Phase'])], axis = 1)
aic_cont_train.index.name = 'AIC_cont'
aic_cont_train

,Phase,Counts,Log,Categ,Bin,AIC_Min
AIC_cont,,,,,,
Adverse_Counts,df1,[11836.0],[11834.0],NaN,[11822.0],Adverse_Bin
Adverse_System_Counts,df1,[11777.0],[11803.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df1,[11829.0],[11808.0],[11824.0],NaN,Arm_Counts_Log
City_Counts,df1,[11652.0],[11474.0],[11539.0],NaN,City_Counts_Log
Country_Counts,df1,[11687.0],[11627.0],NaN,[11625.0],Global_Bin
Continent_Counts,df1,[11647.0],[11634.0],[11630.0],NaN,Continent_Categ
Enrollment_Counts,df1,[11423.0],[10555.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df1,[11830.0],[11823.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df2,[15713.0],[15763.0],NaN,[15735.0],Adverse_Counts
Adverse_System_Counts,df2,[15787.0],[15765.0],NaN,NaN,Adverse_System_Counts_Log
Arm_Counts,df2,[15706.0],[15683.0],[15737.0],NaN,Arm_Counts_Log
City_Counts,df2,[15798.0],[15798.0],[15799.0],NaN,City_Counts
Country_Counts,df2,[15784.0],[15783.0],NaN,[15795.0],Country_Counts_Log
Continent_Counts,df2,[15771.0],[15769.0],[15774.0],NaN,Continent_Counts_Log
Enrollment_Counts,df2,[15085.0],[13006.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df2,[15798.0],[15798.0],NaN,NaN,Funder_Counts
Adverse_Counts,df3,[8317.0],[8298.0],NaN,[8324.0],Adverse_Counts_Log
Adverse_System_Counts,df3,[8323.0],[8324.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df3,[8312.0],[8314.0],[8309.0],NaN,Arm_Categ
City_Counts,df3,[8297.0],[8303.0],[8305.0],NaN,City_Counts
Country_Counts,df3,[8277.0],[8279.0],NaN,[8290.0],Country_Counts
Continent_Counts,df3,[8278.0],[8277.0],[8286.0],NaN,Continent_Counts_Log
Enrollment_Counts,df3,[8284.0],[7537.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df3,[8321.0],[8318.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df4,[7220.0],[7241.0],NaN,[7268.0],Adverse_Counts
Adverse_System_Counts,df4,[7268.0],[7270.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df4,[7263.0],[7265.0],[7256.0],NaN,Arm_Categ
City_Counts,df4,[7268.0],[7270.0],[7270.0],NaN,City_Counts
Country_Counts,df4,[7270.0],[7270.0],NaN,[7270.0],Country_Counts
Continent_Counts,df4,[7270.0],[7270.0],[7270.0],NaN,Continent_Counts
Enrollment_Counts,df4,[7265.0],[5780.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df4,[7270.0],[7270.0],NaN,NaN,Funder_Counts

## AIC Categ

In [13]:
aic_categ_train1['Phase'] = 'df1'
aic_categ_train2['Phase'] = 'df2'
aic_categ_train3['Phase'] = 'df3'
aic_categ_train4['Phase'] = 'df4'

aic_categ_trains = [aic_categ_train1, 
         aic_categ_train2, 
         aic_categ_train3, 
         aic_categ_train4]

aic_categ_train = pd.concat(aic_cont_trains, axis = 0)
aic_categ_train = pd.concat([aic_categ_train['Phase'], aic_categ_train.drop(columns = ['Phase'])], axis = 1)
aic_categ_train.index.name = 'AIC_categ'
aic_categ_train

,Phase,Counts,Log,Categ,Bin,AIC_Min
AIC_categ,,,,,,
Adverse_Counts,df1,[11836.0],[11834.0],NaN,[11822.0],Adverse_Bin
Adverse_System_Counts,df1,[11777.0],[11803.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df1,[11829.0],[11808.0],[11824.0],NaN,Arm_Counts_Log
City_Counts,df1,[11652.0],[11474.0],[11539.0],NaN,City_Counts_Log
Country_Counts,df1,[11687.0],[11627.0],NaN,[11625.0],Global_Bin
Continent_Counts,df1,[11647.0],[11634.0],[11630.0],NaN,Continent_Categ
Enrollment_Counts,df1,[11423.0],[10555.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df1,[11830.0],[11823.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df2,[15713.0],[15763.0],NaN,[15735.0],Adverse_Counts
Adverse_System_Counts,df2,[15787.0],[15765.0],NaN,NaN,Adverse_System_Counts_Log
Arm_Counts,df2,[15706.0],[15683.0],[15737.0],NaN,Arm_Counts_Log
City_Counts,df2,[15798.0],[15798.0],[15799.0],NaN,City_Counts
Country_Counts,df2,[15784.0],[15783.0],NaN,[15795.0],Country_Counts_Log
Continent_Counts,df2,[15771.0],[15769.0],[15774.0],NaN,Continent_Counts_Log
Enrollment_Counts,df2,[15085.0],[13006.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df2,[15798.0],[15798.0],NaN,NaN,Funder_Counts
Adverse_Counts,df3,[8317.0],[8298.0],NaN,[8324.0],Adverse_Counts_Log
Adverse_System_Counts,df3,[8323.0],[8324.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df3,[8312.0],[8314.0],[8309.0],NaN,Arm_Categ
City_Counts,df3,[8297.0],[8303.0],[8305.0],NaN,City_Counts
Country_Counts,df3,[8277.0],[8279.0],NaN,[8290.0],Country_Counts
Continent_Counts,df3,[8278.0],[8277.0],[8286.0],NaN,Continent_Counts_Log
Enrollment_Counts,df3,[8284.0],[7537.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df3,[8321.0],[8318.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df4,[7220.0],[7241.0],NaN,[7268.0],Adverse_Counts
Adverse_System_Counts,df4,[7268.0],[7270.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df4,[7263.0],[7265.0],[7256.0],NaN,Arm_Categ
City_Counts,df4,[7268.0],[7270.0],[7270.0],NaN,City_Counts
Country_Counts,df4,[7270.0],[7270.0],NaN,[7270.0],Country_Counts
Continent_Counts,df4,[7270.0],[7270.0],[7270.0],NaN,Continent_Counts
Enrollment_Counts,df4,[7265.0],[5780.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df4,[7270.0],[7270.0],NaN,NaN,Funder_Counts

# Termination

In [14]:
my_terminations = pd.read_pickle(r".\df_sql\my_terminations.pkl")
my_terminations2 = my_terminations[~my_terminations['phase'].isin(['PHASE1/PHASE2','PHASE2/PHASE3'])][['phase', 'why_stopped2']]

term_pivot = pd.pivot_table(
    data=my_terminations2,
    values='phase',          
    index='why_stopped2',
    columns='phase',
    aggfunc='size',          
    fill_value=0             
)

term_pivot

phase           PHASE1  PHASE2  PHASE3  PHASE4
why_stopped2
Administration     384     514     198     230
Covid               35      91      30      71
Efficacy           258     455     268      50
Enrollment        1331    2950    1127    1479
Funding           1037    1288     574     356