# Libraries

In [104]:
import pandas as pd
import numpy as np
from functools import reduce

# Load Tables

In [105]:
df = pd.read_pickle(r".\df_data\df.pkl")
df1 = pd.read_pickle(r".\df_data\df1.pkl")
df2 = pd.read_pickle(r".\df_data\df2.pkl")
df3 = pd.read_pickle(r".\df_data\df3.pkl")
df4 = pd.read_pickle(r".\df_data\df4.pkl")

medians = pd.read_pickle(r".\df_data\medians.pkl")

pivots1 = pd.read_pickle(r".\p_values\pivots1_vizual.pkl")
pivots2 = pd.read_pickle(r".\p_values\pivots2_vizual.pkl")
pivots3 = pd.read_pickle(r".\p_values\pivots3_vizual.pkl")
pivots4 = pd.read_pickle(r".\p_values\pivots4_vizual.pkl")

pivots_train1 = pd.read_pickle(r".\p_values\pivots1_vizual_train.pkl")
pivots_train2 = pd.read_pickle(r".\p_values\pivots2_vizual_train.pkl")
pivots_train3 = pd.read_pickle(r".\p_values\pivots3_vizual_train.pkl")
pivots_train4 = pd.read_pickle(r".\p_values\pivots4_vizual_train.pkl")

p_cl_train1 = pd.read_pickle(r".\p_values\p_cl1_vizual_train.pkl")
p_cl_train2 = pd.read_pickle(r".\p_values\p_cl2_vizual_train.pkl")
p_cl_train3 = pd.read_pickle(r".\p_values\p_cl3_vizual_train.pkl")
p_cl_train4 = pd.read_pickle(r".\p_values\p_cl4_vizual_train.pkl")

chi_train1 = pd.read_pickle(r".\p_values\chi1_vizual_train.pkl")
chi_train2 = pd.read_pickle(r".\p_values\chi2_vizual_train.pkl")
chi_train3 = pd.read_pickle(r".\p_values\chi3_vizual_train.pkl")
chi_train4 = pd.read_pickle(r".\p_values\chi4_vizual_train.pkl")

mann_train1 = pd.read_pickle(r".\p_values\mann_whit1_vizual_train.pkl")
mann_train2 = pd.read_pickle(r".\p_values\mann_whit2_vizual_train.pkl")
mann_train3 = pd.read_pickle(r".\p_values\mann_whit3_vizual_train.pkl")
mann_train4 = pd.read_pickle(r".\p_values\mann_whit4_vizual_train.pkl")

aic_cont_train1 = pd.read_pickle(r".\p_values\aic_counts1_vizual_train.pkl")
aic_cont_train2 = pd.read_pickle(r".\p_values\aic_counts2_vizual_train.pkl")
aic_cont_train3 = pd.read_pickle(r".\p_values\aic_counts3_vizual_train.pkl")
aic_cont_train4 = pd.read_pickle(r".\p_values\aic_counts4_vizual_train.pkl")

aic_categ_train1 = pd.read_pickle(r".\p_values\aic_categ1_vizual_train.pkl")
aic_categ_train2 = pd.read_pickle(r".\p_values\aic_categ2_vizual_train.pkl")
aic_categ_train3 = pd.read_pickle(r".\p_values\aic_categ3_vizual_train.pkl")
aic_categ_train4 = pd.read_pickle(r".\p_values\aic_categ4_vizual_train.pkl")

# Medians (Full data)

In [106]:
medians[['Enrollment', 'Adverse', 'Arm', 'City', 'Country', 'Continent', 'Completion_Gap']]

        Enrollment  Adverse  Arm  City  Country  Continent  Completion_Gap
df1           28.0      0.0  2.0   1.0      1.0        1.0            11.0
df2           44.0      0.0  2.0   1.0      1.0        1.0            25.0
df3          189.5      0.0  2.0   5.0      1.0        1.0            24.0
df4           60.5      0.0  2.0   1.0      1.0        1.0            21.0
Mean          80.5      0.0  2.0   2.0      1.0        1.0           20.25
Median       52.25      0.0  2.0   1.0      1.0        1.0            22.5

In [107]:
# Columns for which distribution is more wide --> May be kept as Log
medians_categ = medians.loc[:, medians.loc["Median"] > 5]
categ_cols = medians_categ.columns.to_list()
drop_categ_cols = [col + "_Categ" for col in categ_cols]

# Columns with almost all distribution around lower values e.g., 0, 1 ,2
medians_log = medians.loc[:, medians.loc["Median"] < 5]
drop_log_cols = [col for col in df1.columns 
                 if "_Log" in col and any(name in col for name in medians_log)]

display(drop_log_cols)

['Adverse_Counts_Log',
 'Adverse_System_Counts_Log',
 'Arm_Counts_Log',
 'Country_Counts_Log',
 'Continent_Counts_Log',
 'City_Counts_Log']

# Pivots

## Pivots (Full Data)

In [108]:
pivots1.index.names = ['Variable', 'Level']
pivots2.index.names = ['Variable', 'Level']
pivots3.index.names = ['Variable', 'Level']
pivots4.index.names = ['Variable', 'Level']
pivots1.index.names

FrozenList(['Variable', 'Level'])

In [109]:
pivots = pivots1.merge(pivots2, on = ['Variable','Level'], how = 'outer')
pivots = pivots.merge(pivots3, on = ['Variable','Level'], how = 'outer')
pivots = pivots.merge(pivots4, on = ['Variable','Level'], how = 'outer')
pivots

Study_Status_Bin                  df1_COMPLETED  df1_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No         15623.0          2716.0
                     Adverse_Yes         3023.0           467.0
Adverse_List         Adv_Death           1393.0           270.0
                     Adv_None           15547.0          2708.0
                     Adv_Serious         1152.0           310.0
...                                         ...             ...
Primary_Purpose_List TREATMENT          11515.0          2486.0
Sex_List             FEMALE             15842.0          2992.0
                     MALE               17884.0          3021.0
Standard_Care_Bin    Soc_No             18425.0          3078.0
                     Soc_Yes              221.0           105.0

Study_Status_Bin                  df2_COMPLETED  df2_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          8512.0          3293.0
                     Adverse_Yes         7292.0          2131.0
Adverse_List         Adv_Death           4067.0          1262.0
                     Adv_None            8395.0          3237.0
                     Adv_Serious         5527.0          1552.0
...                                         ...             ...
Primary_Purpose_List TREATMENT          13236.0          4778.0
Sex_List             FEMALE             15171.0          5204.0
                     MALE               14519.0          5061.0
Standard_Care_Bin    Soc_No             15171.0          5077.0
                     Soc_Yes              633.0           347.0

Study_Status_Bin                  df3_COMPLETED  df3_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          5677.0          1534.0
                     Adverse_Yes         5880.0           875.0
Adverse_List         Adv_Death           3860.0           573.0
                     Adv_None            5586.0          1513.0
                     Adv_Serious         5173.0           730.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           9355.0          2035.0
Sex_List             FEMALE             11221.0          2339.0
                     MALE               10584.0          2209.0
Standard_Care_Bin    Soc_No             11089.0          2223.0
                     Soc_Yes              468.0           186.0

Study_Status_Bin                  df4_COMPLETED  df4_TERMINATED
Variable             Level
Adverse_Bin          Adverse_No          8210.0          1912.0
                     Adverse_Yes         2727.0           397.0
Adverse_List         Adv_Death           1585.0           235.0
                     Adv_None            7904.0          1846.0
                     Adv_Serious         1591.0           195.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           7459.0          1679.0
Sex_List             FEMALE             10594.0          2259.0
                     MALE                9670.0          2054.0
Standard_Care_Bin    Soc_No             10508.0          2141.0
                     Soc_Yes              429.0           168.0

[164 rows x 8 columns]

## Pivots (Train Data)

In [110]:
pivots_train1.index.names = ['Variable', 'Level']
pivots_train2.index.names = ['Variable', 'Level']
pivots_train3.index.names = ['Variable', 'Level']
pivots_train4.index.names = ['Variable', 'Level']

In [111]:
pivots_train = pivots_train1.merge(pivots_train2, on = ['Variable','Level'], how = 'outer')
pivots_train = pivots_train.merge(pivots_train3, on = ['Variable','Level'], how = 'outer')
pivots_train = pivots_train.merge(pivots_train4, on = ['Variable','Level'], how = 'outer')
pivots_train

Study_Status_Bin                  df1_COMPLETED  df1_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No         12505.0          2161.0
                     Adverse_Yes         2412.0           385.0
Adverse_List         Adv_Death           1118.0           213.0
                     Adv_None           12446.0          2153.0
                     Adv_Serious          934.0           243.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           9212.0          1977.0
Sex_List             FEMALE             12676.0          2388.0
                     MALE               14329.0          2413.0
Standard_Care_Bin    Soc_No             14745.0          2455.0
                     Soc_Yes              172.0            91.0

Study_Status_Bin                  df2_COMPLETED  df2_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          6807.0          2644.0
                     Adverse_Yes         5836.0          1695.0
Adverse_List         Adv_Death           3271.0          1031.0
                     Adv_None            6716.0          2595.0
                     Adv_Serious         4436.0          1246.0
...                                         ...             ...
Primary_Purpose_List TREATMENT          10589.0          3812.0
Sex_List             FEMALE             12149.0          4164.0
                     MALE               11609.0          4053.0
Standard_Care_Bin    Soc_No             12159.0          4061.0
                     Soc_Yes              484.0           278.0

Study_Status_Bin                  df3_COMPLETED  df3_TERMINATED  \
Variable             Level
Adverse_Bin          Adverse_No          4532.0          1228.0
                     Adverse_Yes         4713.0           699.0
Adverse_List         Adv_Death           3089.0           448.0
                     Adv_None            4456.0          1210.0
                     Adv_Serious         4146.0           577.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           7482.0          1633.0
Sex_List             FEMALE              8977.0          1871.0
                     MALE                8476.0          1766.0
Standard_Care_Bin    Soc_No              8885.0          1783.0
                     Soc_Yes              360.0           144.0

Study_Status_Bin                  df4_COMPLETED  df4_TERMINATED
Variable             Level
Adverse_Bin          Adverse_No          6595.0          1532.0
                     Adverse_Yes         2154.0           315.0
Adverse_List         Adv_Death           1254.0           191.0
                     Adv_None            6340.0          1478.0
                     Adv_Serious         1257.0           155.0
...                                         ...             ...
Primary_Purpose_List TREATMENT           5953.0          1342.0
Sex_List             FEMALE              8465.0          1805.0
                     MALE                7725.0          1644.0
Standard_Care_Bin    Soc_No              8406.0          1705.0
                     Soc_Yes              343.0           142.0

[164 rows x 8 columns]

# P_values

## P_values (Train data)

In [125]:
p_cls_train = [p_cl_train1[['Variable', 'df1_Stat_Sig']].rename(columns = {'df1_Stat_Sig': 'df1'}), 
         p_cl_train2[['Variable', 'df2_Stat_Sig']].rename(columns = {'df2_Stat_Sig': 'df2'}), 
         p_cl_train3[['Variable', 'df3_Stat_Sig']].rename(columns = {'df3_Stat_Sig': 'df3'}), 
         p_cl_train4[['Variable', 'df4_Stat_Sig']].rename(columns = {'df4_Stat_Sig': 'df4'})]

p_cl_train = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), p_cls_train)
p_cl_train.index.name = 'p_cl'
p_cl_train

,Variable,df1,df2,df3,df4
p_cl,,,,,
0,ADULT,Stat_Sig,-,-,-
1,Adv_Death,-,Stat_Sig,-,-
2,Adv_Serious,Stat_Sig,Stat_Sig,Stat_Sig,Stat_Sig
3,"Adv_Syst_Blood, Lymphatic, Endocrine",Stat_Sig,Stat_Sig,Stat_Sig,-
4,Adv_Syst_Cardio,-,Stat_Sig,-,-
...,...,...,...,...,...
109,Surgical,Stat_Sig,Stat_Sig,Stat_Sig,-
110,TREATMENT,Stat_Sig,Stat_Sig,-,-
111,TRIPLE,Stat_Sig,Stat_Sig,-,Stat_Sig
112,Topical,Stat_Sig,Stat_Sig,-,-
113,"Urogenital, Pregnancy",-,-,-,Stat_Sig

# Chi2

## Chi2 (Train data)

In [120]:
chi_trains = [chi_train1[['Variable', 'df1_Stat_Sig']].rename(columns = {'df1_Stat_Sig': 'df1'}), 
         chi_train2[['Variable', 'df2_Stat_Sig']].rename(columns = {'df2_Stat_Sig': 'df2'}), 
         chi_train3[['Variable', 'df3_Stat_Sig']].rename(columns = {'df3_Stat_Sig': 'df3'}), 
         chi_train4[['Variable', 'df4_Stat_Sig']].rename(columns = {'df4_Stat_Sig': 'df4'})]

chi_train = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), chi_trains)
chi_train.index.name = 'Chi2'
chi_train

                      Variable       df1       df2       df3       df4
Chi2
0                  Adverse_Bin         -  Stat_Sig  Stat_Sig  Stat_Sig
1         Adverse_System_Categ         -  Stat_Sig  Stat_Sig  Stat_Sig
2               Allocation_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
3                    Arm_Categ  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
4                   City_Categ  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
5              Continent_Categ  Stat_Sig         -         -  Stat_Sig
6                 Covid_19_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
7             Enrollment_Categ  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
8          Funder_Industry_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
9                   Global_Bin  Stat_Sig  Stat_Sig         -  Stat_Sig
10                 Healthy_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
11    Intervention_Route_Categ  Stat_Sig  Stat_Sig         -         -
12     Intervention_Type_Categ  Stat_Sig  Stat_Sig         -         -
13                 Placebo_Bin  Stat_Sig  Stat_Sig  Stat_Sig         -
14           Standard_Care_Bin  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig

## Mann Whitney (Train data)

In [121]:
mann_trains = [mann_train1[['Variable', 'df1_Stat_Sig']].rename(columns = {'df1_Stat_Sig': 'df1'}), 
         mann_train2[['Variable', 'df2_Stat_Sig']].rename(columns = {'df2_Stat_Sig': 'df2'}), 
         mann_train3[['Variable', 'df3_Stat_Sig']].rename(columns = {'df3_Stat_Sig': 'df3'}), 
         mann_train4[['Variable', 'df4_Stat_Sig']].rename(columns = {'df4_Stat_Sig': 'df4'})]

mann_train = reduce(lambda left, right: pd.merge(left, right, on='Variable', how='outer'), mann_trains)
mann_train.index.name = 'Mann'
mann_train

                       Variable       df1       df2       df3       df4
Mann
0                Adverse_Counts         -  Stat_Sig  Stat_Sig  Stat_Sig
1            Adverse_Counts_Log         -  Stat_Sig  Stat_Sig  Stat_Sig
2         Adverse_System_Counts         -  Stat_Sig  Stat_Sig  Stat_Sig
3     Adverse_System_Counts_Log         -  Stat_Sig  Stat_Sig  Stat_Sig
4                    Arm_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
5                Arm_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
6                   City_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
7               City_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
8              Continent_Counts         -  Stat_Sig  Stat_Sig  Stat_Sig
9          Continent_Counts_Log         -  Stat_Sig  Stat_Sig  Stat_Sig
10               Country_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
11           Country_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
12            Enrollment_Counts  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
13        Enrollment_Counts_Log  Stat_Sig  Stat_Sig  Stat_Sig  Stat_Sig
14                Funder_Counts  Stat_Sig         -  Stat_Sig         -
15            Funder_Counts_Log  Stat_Sig         -  Stat_Sig         -
16    Intervention_Route_Counts  Stat_Sig  Stat_Sig         -         -
17     Intervention_Type_Counts  Stat_Sig  Stat_Sig         -         -

# AIC

## AIC Counts

In [122]:
aic_cont_train1['Phase'] = 'df1'
aic_cont_train2['Phase'] = 'df2'
aic_cont_train3['Phase'] = 'df3'
aic_cont_train4['Phase'] = 'df4'

aic_cont_trains = [aic_cont_train1, 
         aic_cont_train2, 
         aic_cont_train3, 
         aic_cont_train4]

aic_cont_train = pd.concat(aic_cont_trains, axis = 0)
aic_cont_train = pd.concat([aic_cont_train['Phase'], aic_cont_train.drop(columns = ['Phase'])], axis = 1)
aic_cont_train.index.name = 'AIC_cont'
aic_cont_train

,Phase,Counts,Log,Categ,Bin,AIC_Min
AIC_cont,,,,,,
Adverse_Counts,df1,[14498.0],[14497.0],NaN,[14508.0],Adverse_Counts_Log
Adverse_System_Counts,df1,[14502.0],[14510.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df1,[14467.0],[14420.0],[14468.0],NaN,Arm_Counts_Log
City_Counts,df1,[14430.0],[14430.0],[14353.0],NaN,City_Categ
Country_Counts,df1,[14483.0],[14510.0],NaN,[14426.0],Global_Bin
Continent_Counts,df1,[14503.0],[14508.0],[14413.0],NaN,Continent_Categ
Enrollment_Counts,df1,[13180.0],[10812.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df1,[14497.0],[14487.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df2,[19068.0],[18943.0],NaN,[19240.0],Adverse_Counts_Log
Adverse_System_Counts,df2,[19228.0],[19228.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df2,[19126.0],[19112.0],[19196.0],NaN,Arm_Counts_Log
City_Counts,df2,[19258.0],[19163.0],[19212.0],NaN,City_Counts_Log
Country_Counts,df2,[19302.0],[19254.0],NaN,[19294.0],Country_Counts_Log
Continent_Counts,df2,[19299.0],[19282.0],[19305.0],NaN,Continent_Counts_Log
Enrollment_Counts,df2,[17532.0],[13210.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df2,[19305.0],[19306.0],NaN,NaN,Funder_Counts
Adverse_Counts,df3,[10222.0],[10037.0],NaN,[10138.0],Adverse_Counts_Log
Adverse_System_Counts,df3,[10188.0],[10152.0],NaN,NaN,Adverse_System_Counts_Log
Arm_Counts,df3,[10267.0],[10271.0],[10262.0],NaN,Arm_Categ
City_Counts,df3,[10278.0],[10244.0],[10251.0],NaN,City_Counts_Log
Country_Counts,df3,[10277.0],[10272.0],NaN,[10278.0],Country_Counts_Log
Continent_Counts,df3,[10277.0],[10272.0],[10277.0],NaN,Continent_Counts_Log
Enrollment_Counts,df3,[10115.0],[7782.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df3,[10276.0],[10275.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df4,[9691.0],[9659.0],NaN,[9757.0],Adverse_Counts_Log
Adverse_System_Counts,df4,[9752.0],[9743.0],NaN,NaN,Adverse_System_Counts_Log
Arm_Counts,df4,[9782.0],[9783.0],[9770.0],NaN,Arm_Categ
City_Counts,df4,[9786.0],[9773.0],[9802.0],NaN,City_Counts_Log
Country_Counts,df4,[9782.0],[9743.0],NaN,[9794.0],Country_Counts_Log
Continent_Counts,df4,[9807.0],[9800.0],[9801.0],NaN,Continent_Counts_Log
Enrollment_Counts,df4,[9786.0],[6008.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df4,[9803.0],[9806.0],NaN,NaN,Funder_Counts

## AIC Categ

In [123]:
aic_categ_train1['Phase'] = 'df1'
aic_categ_train2['Phase'] = 'df2'
aic_categ_train3['Phase'] = 'df3'
aic_categ_train4['Phase'] = 'df4'

aic_categ_trains = [aic_categ_train1, 
         aic_categ_train2, 
         aic_categ_train3, 
         aic_categ_train4]

aic_categ_train = pd.concat(aic_cont_trains, axis = 0)
aic_categ_train = pd.concat([aic_categ_train['Phase'], aic_categ_train.drop(columns = ['Phase'])], axis = 1)
aic_categ_train.index.name = 'AIC_categ'
aic_categ_train

,Phase,Counts,Log,Categ,Bin,AIC_Min
AIC_categ,,,,,,
Adverse_Counts,df1,[14498.0],[14497.0],NaN,[14508.0],Adverse_Counts_Log
Adverse_System_Counts,df1,[14502.0],[14510.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df1,[14467.0],[14420.0],[14468.0],NaN,Arm_Counts_Log
City_Counts,df1,[14430.0],[14430.0],[14353.0],NaN,City_Categ
Country_Counts,df1,[14483.0],[14510.0],NaN,[14426.0],Global_Bin
Continent_Counts,df1,[14503.0],[14508.0],[14413.0],NaN,Continent_Categ
Enrollment_Counts,df1,[13180.0],[10812.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df1,[14497.0],[14487.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df2,[19068.0],[18943.0],NaN,[19240.0],Adverse_Counts_Log
Adverse_System_Counts,df2,[19228.0],[19228.0],NaN,NaN,Adverse_System_Counts
Arm_Counts,df2,[19126.0],[19112.0],[19196.0],NaN,Arm_Counts_Log
City_Counts,df2,[19258.0],[19163.0],[19212.0],NaN,City_Counts_Log
Country_Counts,df2,[19302.0],[19254.0],NaN,[19294.0],Country_Counts_Log
Continent_Counts,df2,[19299.0],[19282.0],[19305.0],NaN,Continent_Counts_Log
Enrollment_Counts,df2,[17532.0],[13210.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df2,[19305.0],[19306.0],NaN,NaN,Funder_Counts
Adverse_Counts,df3,[10222.0],[10037.0],NaN,[10138.0],Adverse_Counts_Log
Adverse_System_Counts,df3,[10188.0],[10152.0],NaN,NaN,Adverse_System_Counts_Log
Arm_Counts,df3,[10267.0],[10271.0],[10262.0],NaN,Arm_Categ
City_Counts,df3,[10278.0],[10244.0],[10251.0],NaN,City_Counts_Log
Country_Counts,df3,[10277.0],[10272.0],NaN,[10278.0],Country_Counts_Log
Continent_Counts,df3,[10277.0],[10272.0],[10277.0],NaN,Continent_Counts_Log
Enrollment_Counts,df3,[10115.0],[7782.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df3,[10276.0],[10275.0],NaN,NaN,Funder_Counts_Log
Adverse_Counts,df4,[9691.0],[9659.0],NaN,[9757.0],Adverse_Counts_Log
Adverse_System_Counts,df4,[9752.0],[9743.0],NaN,NaN,Adverse_System_Counts_Log
Arm_Counts,df4,[9782.0],[9783.0],[9770.0],NaN,Arm_Categ
City_Counts,df4,[9786.0],[9773.0],[9802.0],NaN,City_Counts_Log
Country_Counts,df4,[9782.0],[9743.0],NaN,[9794.0],Country_Counts_Log
Continent_Counts,df4,[9807.0],[9800.0],[9801.0],NaN,Continent_Counts_Log
Enrollment_Counts,df4,[9786.0],[6008.0],NaN,NaN,Enrollment_Counts_Log
Funder_Counts,df4,[9803.0],[9806.0],NaN,NaN,Funder_Counts